# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: ğŸ“• Documentation Issue
    url: https://github.com/open-constructs/cdk-terrain
    about: Documentation will be migrated in soon
  - name: â“ Question
    url: https://cdk.dev
    about: ğŸ™‹ For usage questions that may not require a core maintainer to answer, post in our community's cdk-terrain channel
